### ISSUE TITLE
Surround output on incorrect Channels

### ISSUE THREAD

**Issue by Reemtsman** [xbmc/audiodecoder.sacd#15]
I am using a 7.1 Loudspeaker Setup with
C Center
FL Front Left
FR Front Right
L Leftt
R Right
RL Rear Left
RR Rear Right
SW Subwoofer

7.1.4 to be precise but as Kodi does not allow the setup of Hight Speakers the .4 are irrelevant. Kodi is set to a 5.1 Speaker Layout (Kodi Player is not used for Movies. therefore Layout is sat to 5.1 for best match to the Layout for Multichannel SACD Playback), Passthrough is enabled. Connetcion to the AVR is through HDMI. All Speakers are Full Range.

Addon is set to Multichannel wich works in general but i realized that the surround channels are played incorrectly on RL and RR instead of L and R.
When checking the signal Type received by the AVR this shows 7.1 PCM. This is strange because like mentioned Kodi is only set to 5.1, not 7.1.
How can i arrange the Surround channels are played correctly on L and R?

**Comment by fritsch** [comment]
Post your debuglog. If you see that kodi only opens 6 channels and not 7.1 - then Android / whatever OS you are using is doing that by its own intention.

**Comment by fritsch** [comment]
For bitperfect audio in general, you should use an OS that can open "direct connections" to the sound hardware, e.g. Windows + WASAPI or Linux with ALSA.

On Android in general you rely on the "soundserver" which is Audiotrack. So whatever kodi can do is just "get it right" out of kodi, afterwards the OS does whatever it wants. The really only way around this (100%) is using a format that they can't touch with a sink that they can't touch. This is IEC passthrough. So you won't like this, but if you convert the SACD to e.g. truehd, dts-hd - Android can not break it as it's then kodi doing the IEC packing and outputting without Android touching it IF your AVR / whatever supports that kind of format and the Android box needs to as well (IEC format that is).

For the other passthrough format (RAW), Android has the say in packing ... therefore breaks it again :-)

For PCM content that is not passed through, but decode to PCM and output with the "best capability" the device offers from kodi's POV. Afterwards the soundserver (audiotrack) takes over and does whatever it wants ...

As a founded conclusion: If you want high quality pcm / flac / whatever audio in all cases Android is the wrong choice.

**Comment by Reemtsman** [comment]
Thank you @fritsch for this qualified feedback!
Now that i know what WASAPI Stands for i was so brave to use it and guess what: Stereo arrives as 2.0 PCM at the AVR and Multicahannel as 5.1 PCM with the correct Surround Channels adressed. Mission Acomplished!

Now just #11 and #14 must be adressed to make this "the Add-on of the month".

And when playing with the All/Stereo/Multichannel Preset i found some strange behaviours. But this doese not belong here. I will open a separate issue for that.

**Comment by Reemtsman** [comment]
@the admins: This can be marked as closed,
