### ISSUE TITLE
Stuttering multichannel audio output

### ISSUE THREAD

**Issue by origpumu** [xbmc/audiodecoder.sacd#19]
Hello,

Playback in stereo works fine. Thanks for the great work!

But when I play a multichannel title, the audio output stutters. Are there any minimum hardware requirements for the plugin?

I use a matrix nightly build (20210522-d173893 RPi2.arm) on my raspberry pi 3. A Pioneer lx86 is connected via HDMI.

Multichannel FLAC, movies and so on work perfectly. Stereo SACD iso files will work too. Only the multi-channel titles of all SACDs stutter.

I tested various settings in the audio section (5.1, 5.0, 7.1, optimized, fix, best match, alsa output devices vc4-hdmi, passthrough on or off). Also tried local and files from a NFS share. 

Regards,
Peter.

**Comment by HeresJonny** [comment]
That will definitely be a hardware limit. MC SACD decoding requires much more horsepower than MC FLAC. If you want to use a small form factor device you will have to go with an ODROID N2 (+) or similar.

**Comment by origpumu** [comment]
Thx for your reply. Could a RPi4 be enough? Has anyone tested this yet?

**Comment by origpumu** [comment]
I can give the answer myself now. Bought an RPi4, tried playing multichannel-SACDs. it works!
Thx for Your great work!
