### ISSUE TITLE
Sort playlist by channel

### ISSUE THREAD

**Issue by HeresJonny** [xbmc/audiodecoder.sacd#5]
When presenting sacdstreams of an iso as tracks, sorting by track in the blade menu should sort by channel info, i.e. all stereo tracks first, then all multichannel tracks.

**Comment by AlwinEsch** [comment]
I added a new function in settings, which allows to sort the list, first all stereo and then the multichannel.

![Bildschirmfoto von 2021-09-27 15-22-22](https://user-images.githubusercontent.com/6879739/134953912-2b9ce9b8-691a-49f8-b399-65f6255d76b1.png)

In addition, the fallback problem has been resolved, if there are no multichannel choices, for example, it will revert to using stereo (unless it is deactivated again in the add-on's expert settings)

See pull request here https://github.com/xbmc/audiodecoder.sacd/pull/35.

**Comment by AlwinEsch** [comment]
New version 19.0.0 released where sort option is added.
